import http from 'k6/http';

// ฟังก์ชันตาม path สุดท้าย: "action.php"
export function action() {
    const cid = `${__VU}${__ITER}`;
    const url = 'https://testolr2.thaijobjob.com/2025074/action.php';

    const payload = JSON.stringify({
        "form": {
            "HdPosition": "101",
            "AreaID": "",
            "Position": "โปรแกรมเมอร์",
            "Name1": "นาง",
            "Name2": "ทดสอบ",
            "Name3": "ระบบ",
            "NameEng1": "Mr",
            "NameEng2": "Test",
            "NameEng3": "Test",
            "CustomerID": ""+cid,
            "Sex": "ชาย",
            "Nationality": "ไทย",
            "Nationalism": "ไทย",
            "Religion": "พุทธ",
            "Status": "โสด",
            "DateofBirth": "01/01/2539",
            "DateofBirthYear": "31",
            "DateofBirthMonth": "1",
            "CusIDStart": "03/07/2568",
            "CusIDStop": "16/07/2568",
            "CusIDAmphur": "เมือง",
            "CusIDProvince": "ขอนแก่น",
            "Homeland": "ขอนแก่น",
            "RelSoldier": "ผ่านเกณฑ์ทหารแล้ว",
            "Address": "1",
            "Building": "หมู่บ้านทดสอบ",
            "Moo": "99",
            "Soi": "12",
            "Road": "ทดสอบ",
            "District": "ในเมือง",
            "Amphur": "เมือง",
            "Province": "ขอนแก่น",
            "Zipcode": "40000",
            "TelHome": "0444444444",
            "TelMobile": "0830197004",
            "Email": "dev@dev.com",
            "Line": "testDev007",
            "RegisAddress": "1",
            "RegisVillage": "หมู่บ้านทดสอบ",
            "RegisMoo": "99",
            "RegisAlleys": "12",
            "RegisRoad": "ทดสอบ",
            "RegisSubDistrict": "ในเมือง",
            "RegisDistrict": "เมือง",
            "RegisProvince": "ขอนแก่น",
            "RegisZipcode": "40000",
            "Degree": "ปริญญาเอก",
            "DegreeName": "วิทยาศาสตรบัณฑิต",
            "Major": "สาขาวิชาใดวิชาหนึ่ง",
            "SubMajor": "วิชาเทพซ่า",
            "SchoolName": "มหาวิทยาลัยขอนแก่น",
            "SchoolEnd": "02/07/2568",
            "GPA": "4.00",
            "Cert1": "ได้รับใบอนุญาตประกอบวิชาชีพวิศวกรรมควบคุม ระดับภาคีวิศวกรขึ้นไป",
            "CertNo1": "100001",
            "CertStart1": "10/10/2555",
            "CertStop1": "10/10/2560",
            "Cert2": "มีความรู้ความสามารถในการใช้งานคอมพิวเตอร์พื้นฐาน",
            "CertNo2": "100002",
            "CertStart2": "10/10/2555",
            "CertStop2": "10/10/2560",
            "Cert3": "เทพขั้นที่ 1",
            "CertNo3": "100003",
            "CertStart3": "10/10/2555",
            "CertStop3": "10/10/2560",
            "Cert4": "เทพขั้นที่ 2",
            "CertNo4": "100004",
            "CertStart4": "10/10/2555",
            "CertStop4": "10/10/2560",
            "Cert5": "เทพขั้นที่ 3",
            "CertNo5": "100005",
            "CertStart5": "10/10/2555",
            "CertStop5": "10/10/2560",
            "Ocsc": "เป็นผู้สอบวัดความรู้ความสามารถทั่วไป ระดับปริญญาตรี ของสำนักงาน ก.พ.",
            "OcscNo": "1000054",
            "OcscStart": "12/12/2550",
            "PosYStart1": "09/07/2568",
            "PosYEnd1": "30/07/2568",
            "DegreeRow1": "ทดสอบ",
            "MajorRow1": "ทดสอบ",
            "SchoolRow1": "ทดสอบ",
            "GPARow1": "1.23",
            "PosYStart2": "09/07/2568",
            "PosYEnd2": "30/07/2568",
            "DegreeRow2": "ทดสอบ",
            "MajorRow2": "ทดสอบ",
            "SchoolRow2": "ทดสอบ",
            "GPARow2": "3.33",
            "PosYStart3": "09/07/2568",
            "PosYEnd3": "30/07/2568",
            "DegreeRow3": "ทดสอบ",
            "MajorRow3": "ทดสอบ",
            "SchoolRow3": "ทดสอบ",
            "GPARow3": "3",
            "PosYStart4": "09/07/2568",
            "PosYEnd4": "30/07/2568",
            "DegreeRow4": "ทดสอบ",
            "MajorRow4": "ทดสอบ",
            "SchoolRow4": "ทดสอบ",
            "GPARow4": "3.33",
            "PosYStart5": "09/07/2568",
            "PosYEnd5": "30/07/2568",
            "DegreeRow5": "ทดสอบ",
            "MajorRow5": "ทดสอบ",
            "SchoolRow5": "ทดสอบ",
            "GPARow5": "3.33",
            "Language1": "ภาษาไทย",
            "Listening1": "ดีมาก",
            "Speaking1": "เล็กน้อย",
            "Reading1": "เล็กน้อย",
            "Writing1": "เล็กน้อย",
            "Language2": "ภาษาอังกฤษ",
            "Listening2": "ดีมาก",
            "Speaking2": "เล็กน้อย",
            "Reading2": "เล็กน้อย",
            "Writing2": "เล็กน้อย",
            "Language3": " ภาษาเทพ",
            "Listening3": "ดีมาก",
            "Speaking3": "เล็กน้อย",
            "Reading3": "เล็กน้อย",
            "Writing3": "เล็กน้อย",
            "Language4": "ภาษาเขมร",
            "Listening4": "ดีมาก",
            "Speaking4": "ดี",
            "Reading4": "เล็กน้อย",
            "Writing4": "เล็กน้อย",
            "Language5": "ภาษาพม่า",
            "Listening5": "เล็กน้อย",
            "Speaking5": "เล็กน้อย",
            "Reading5": "เล็กน้อย",
            "Writing5": "พอใช้",
            "Disease": "มีความพิการ",
            "DiseaseDetail": "มี4แขน",
            "DiseaseHelp": "ขอใช้คอมพิวเตอร์อ่านออกเสียง สำหรับคนตาบอด (จัดสอบเฉพาะศูนย์สอบกรุงเทพฯและปริมณฑล)",
            "CurrentWork": "ลูกจ้าง/พนักงานราชการในหน่วยงานราชการ",
            "CareerWorkplace": "โรงเรียนทดสอบ",
            "CareerOffice": "ทดสอบ",
            "CareerTelephone": "0899999999",
            "CareerPosition": "เจ้าหน้าที่",
            "CareerStyle": "ขั้น 9",
            "CareerSalary": "50000",
            "CareerDateStart": "07/07/2568",
            "CareerDateEnd": "05/07/2568",
            "CareerReason": "ย้ายที่พัก",
            "CareerDateStart1": "09/02/2560",
            "CareerDateEnd1": "08/07/2568",
            "CareerWorkplace1": "โรงเรียนทดสอบ",
            "CareerPosition1": "เจ้าหน้าที่",
            "CareerSalary1": "15000",
            "CareerReason1": "ย้ายที่พัก",
            "CareerDateStart2": "09/02/2560",
            "CareerDateEnd2": "08/07/2568",
            "CareerWorkplace2": "โรงเรียนทดสอบ",
            "CareerPosition2": "เจ้าหน้าที่",
            "CareerSalary2": "15000",
            "CareerReason2": "ย้ายที่พัก",
            "CareerDateStart3": "09/02/2560",
            "CareerDateEnd3": "08/07/2568",
            "CareerWorkplace3": "โรงเรียนทดสอบ",
            "CareerPosition3": "เจ้าหน้าที่",
            "CareerSalary3": "15000",
            "CareerReason3": "ย้ายที่พัก",
            "CareerDateStart4": "09/02/2560",
            "CareerDateEnd4": "08/07/2568",
            "CareerWorkplace4": "โรงเรียนทดสอบ",
            "CareerPosition4": "เจ้าหน้าที่",
            "CareerSalary4": "15000",
            "CareerReason4": "ย้ายที่พัก",
            "CareerDateStart5": "09/02/2560",
            "CareerDateEnd5": "08/07/2568",
            "CareerWorkplace5": "โรงเรียนทดสอบ",
            "CareerPosition5": "เจ้าหน้าที่",
            "CareerSalary5": "15000",
            "CareerReason5": "ย้ายที่พัก",
            "SpecialType1": "ทดสอบ",
            "Special1": "ทดสอบกรอกไปเรื่อยๆๆๆๆๆๆๆๆๆๆๆๆๆทดสอบกรอกไปเรื่อยๆๆๆๆๆๆๆๆๆๆๆๆๆทดสอบกรอกไปเรื่อยๆๆๆๆๆๆๆๆๆๆๆๆๆทดสอบกรอกไปเรื่อยๆๆๆๆๆๆๆๆๆๆๆๆๆ",
            "SpecialType2": "ความรู้ความสามารถพิเศษ",
            "Special2": "ทดสอบความรู้ความสามารถพิเศษทดสอบความรู้ความสามารถพิเศษทดสอบความรู้ความสามารถพิเศษทดสอบความรู้ความสามารถพิเศษทดสอบความรู้ความสามารถพิเศษทดสอบความรู้ความสามารถพิเศษ",
            "SpecialType3": "ผลงานโดดเด่นที่เกี่ยวข้องกับตำแหน่ง",
            "Special3": "ทดสอบผลงานโดดเด่นที่เกี่ยวข้องกับตำแหน่งทดสอบผลงานโดดเด่นที่เกี่ยวข้องกับตำแหน่งทดสอบผลงานโดดเด่นที่เกี่ยวข้องกับตำแหน่งทดสอบผลงานโดดเด่นที่เกี่ยวข้องกับตำแหน่งทดสอบผลงานโดดเด่นที่",
            "SpecialType4": "คุณลักษณะส่วนบุคคลโดดเด่นที่เกี่ยวข้องกับตำแหน่ง",
            "Special4": "ทดสอบคุณลักษณะส่วนบุคคลโดดเด่นที่เกี่ยวข้องกับตำแหน่งคุณลักษณะส่วนบุคคลโดดเด่นที่เกี่ยวข้องกับตำแหน่งคุณลักษณะส่วนบุคคลโดดเด่นที่เกี่ยวข้องกับตำแหน่งคุณลักษณะส่วนบุคคลโดดเด่นที่เกี่ยวข้องกับตำแหน่ง",
            "GovermentHis": "พนักงานราชการ",
            "GovermentPlace": "ตำรวจ",
            "GovermentPos": "ตรวจ",
            "GovermentStyle": "พลเอก",
            "GovermentTime": "2 ปี",
            "GovermentSalary": "45000",
            "GovermentReason": "ย้ายงาน",
            "Crime_History": "ไม่เคย",
            "Crime_Property": "เคย",
            "TrainingStart1": "22/07/2565",
            "TrainingStop1": "18/10/2568",
            "TrainingPlace1": "ทดสอบ",
            "TrainingTopic1": "ทดสอบ",
            "TrainingDetail1": "ทดสอบ",
            "TrainingStart2": "22/07/2565",
            "TrainingStop2": "18/10/2568",
            "TrainingPlace2": "ทดสอบ",
            "TrainingTopic2": "ทดสอบ",
            "TrainingDetail2": "ทดสอบ",
            "TrainingStart3": "22/07/2565",
            "TrainingStop3": "18/10/2568",
            "TrainingPlace3": "ทดสอบ",
            "TrainingTopic3": "ทดสอบ",
            "TrainingDetail3": "ทดสอบ",
            "TrainingStart4": "22/07/2565",
            "TrainingStop4": "18/10/2568",
            "TrainingPlace4": "ทดสอบ",
            "TrainingTopic4": "ทดสอบ",
            "TrainingDetail4": "ทดสอบ",
            "TrainingStart5": "22/07/2565",
            "TrainingStop5": "18/10/2568",
            "TrainingPlace5": "ทดสอบ",
            "TrainingTopic5": "ทดสอบ",
            "TrainingDetail5": "ทดสอบ",
            "FatherPrefix": "นาย",
            "FatherFirstname": "ทดสอบ",
            "FatherSurname": "ทดสอบ",
            "FatherJob": "ทดสอบ",
            "MotherPrefix": "นางสาว",
            "MotherFirstname": "ทดสอบ",
            "MotherSurname": "ทดสอบ",
            "MotherJob": "ทดสอบ",
            "PersonalPrefix": "นางสาว",
            "PersonalFirstname": "ทดสอบ",
            "PersonalSurname": "ทดสอบ",
            "PersonalRelation": "พี่สาวอ่ะดิ",
            "PersonalTel": "0899999999",
            "Message": "เว็บไซต์หน่วยงาน",
            "smsStatus": "1",
            "upload_file": "[{\"key\":\"file1\",\"label\":\"รูปถ่ายหน้าตรง ไม่สวมหมวก และไม่ใส่แว่นตาสีดำ\",\"name\":\"1_101.1309801379460.file1.jpg\"},{\"key\":\"file2\",\"label\":\"สำเนาระเบียนแสดงผลการเรียน (transcript)\",\"name\":\"2_101.1309801379460.file2.pdf\"},{\"key\":\"file3\",\"label\":\"เอกสารประกอบการสมัคร\",\"name\":\"3_101.1309801379460.file3.pdf\"}]"
        }
    });

    const params = {
        headers: {
            'Content-Type': 'application/json',
        },
    };

    const res = http.post(url, payload, params);

    //console.log(res.body); // log response body
    return res;            // return response
}
